name: pybind11-proj

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build-ubuntu-20:
    name: Ubuntu-20
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Build
      shell: bash
      run: |
        sudo apt install -y cmake make
        python -m pip install pytest
        cmake -B build/ -DCMAKE_BUILD_TYPE=Release
        cmake --build build

    - name: Test
      shell: bash
      run: |
        cd build
        ctest --output-on-failure

    - name: Pip-install
      shell: bash
      run: |
        python -m pip install . -vv
        pytest
